server:
  port: 9000
  
spring:
  application:
    name: WantedChallenge 
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  devtools:
    livereload:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/wanted?serverTimezone=Asia/Seoul
    username: wanted
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver